In [1]:
import numpy as np

In [8]:
#Задание 1. Создайте numpy array с элементами от числа N до 0
n = 18
k = np.arange(0, n)
-np.sort(-k)

array([17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,
        0])

In [22]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали

n=100
arr = np.diag(np.arange(0,n,20))
sum_diag = np.trace(arr)
print(arr)
print(sum_diag)

[[ 0  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 40  0  0]
 [ 0  0  0 60  0]
 [ 0  0  0  0 80]]
200


In [24]:
from numpy import linalg

In [31]:
#Задание 3
#Решите систему уравнений: 
#4x + 2y + z = 4      
#x + 3y = 12          
#5y + 4z = -3
s = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
t = np.array( [4, 12, -3] )
u = linalg.solve(s, t)
print(u)
np.allclose(np.dot(s, linalg.solve(s, t)), t )

[ 0.46666667  3.84444444 -5.55555556]


True

In [32]:
#Задача 4 
#Имеется матрица покупок в интернет-магазине. 
#Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.
#Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [33]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [45]:
def cosine( users_stats, next_user_stats ):
    """
    Подсчет косинуса угла между векторами по их координатам
    """
    newLength = np.linalg.norm(next_user_stats)
    similar = []
    
    for i in users_stats:
        allLength = np.linalg.norm( i )  
        similar = np.dot( i, next_user_stats ) / ( allLength * newLength )
        print(similar)

In [44]:
cosine( users_stats, next_user_stats )

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
